### ISSUE TITLE
on -> start_on and separate resuming on algorithm

### ISSUE THREAD

**Issue by ericniebler** [cplusplus/sender-receiver#113]
<a href="https://github.com/LeeHowes"><img src="https://avatars.githubusercontent.com/u/4451678?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [LeeHowes](https://github.com/LeeHowes)**
_Tuesday Dec 07, 2021 at 18:19 GMT_
_Originally opened as https://github.com/NVIDIA/stdexec/issues/306_

----

A possible narrow solution to #111 

Channelling Michal's suggestion in the call to add a user-facing on algorithm and make the current on an internal-only algorithm.

on(sched, sender) in this case would resume on the scheduler provided by the downstream receiver. 
This sender would propagate sched as the completion scheduler. 

We may or may not want to allow optimising based on the completion_scheduler.

**Comment by ericniebler** [comment]
<a href="https://github.com/LeeHowes"><img src="https://avatars.githubusercontent.com/u/4451678?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [LeeHowes](https://github.com/LeeHowes)**
_Tuesday Dec 07, 2021 at 18:24 GMT_

----

I think to be able to write clean on-based code we still need a let_with_scheduler though.

If we need to inject transfer() to make bulk work, such that this doesn't work:

```
auto foo() {
  return just() | bulk(...);
}
```

```
auto foo() {
  return just() | transfer(sch) | bulk(...);
}
```

`sch` needs to come from somewhere. We can either do that with "on", in this new definition, which is odd but would work:
```
auto foo() {
  return just() | on(inline_scheduler) | bulk(...);
}
```

it introduces inline which is dangerous, but it would resume correctly and let bulk customise.

Or an algorithm that grabs the scheduler from the receiver as a low-level primitive:
```
auto foo() {
  return just() | transfer_to_current_scheduler() | bulk(...);
}
```

or of course a fully scoped algorithm:
```
auto foo() {
  return just() | let_with_scheduler([](auto sched_sender){ return sched_sender | bulk(...) });
}
```

It depends on whether we're talking primitives or full algorithms here though.

**Comment by lewissbaker** [comment]
Note that P2300R10 now has three separate algorithms:  starts_on(), continues_on() and on().
So perhaps this issue is now resolved?

However, I also wonder if the move to lazy customization may have also helped here?
The discussion above seems to indicate a desire to have this `transfer_to_current_scheduler()` operation so that, presumably, it can set the completion-scheduler and therefore allow `bulk()` to customize on the completion-scheduler.

However, with the move to lazy customization, it should be able to customize bulk() using just the current 'domain' obtained from the environment.

@ericniebler do you think this is sufficient to close this issue?
