### ISSUE TITLE
a `split` sender should not start the operation if stop has already been requested

### ISSUE THREAD

**Issue by ericniebler** [cplusplus/sender-receiver#256]
if the receiver passed to connect on a split sender has a stop-token that already has a stop request, this should avoid starting the underlying operation

**Comment by lewissbaker** [comment]
Would this also prevent all other consumers from starting the underlying operation?
i.e. it would be as if the underlying operation completed with set_stopped()

If not, then this could potentially result in non-deterministic/surprising behaviour when there are multiple consumers, as depending on the race between starting the op and the stop-request being issued, the underlying operation can either be started and cancelled for all consumers, or not started and then subsequent consumers can let it run to completion normally.

I think the general cancellation behaviour of `split()` needs a rethink, thought, rather than trying to patch it. I have written up some proposed semantics at #263 - which incorporates this suggestion of not starting the underlying op if a consumer has a stop-request pending at start().

**Comment by lewissbaker** [comment]
@ericniebler Are you ok closing this in favor of #263?

**Comment by ericniebler** [comment]
Sure
