### ISSUE TITLE
Language in when_all spec

### ISSUE THREAD

**Issue by ericniebler** [cplusplus/sender-receiver#30]
<a href="https://github.com/ccotter"><img src="https://avatars.githubusercontent.com/u/1799998?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ccotter](https://github.com/ccotter)**
_Saturday Jul 29, 2023 at 01:51 GMT_
_Originally opened as https://github.com/brycelelbach/wg21_p2300_execution/issues/45_

----

Section 11.9.6.12 for when_all's default implementation states

 > If set_value(r_i, t_i...) is called for every r_i, op_state's associated stop callback optional is reset and set_value(out_r, t_0..., t_1..., ..., t_{n-1}...) is called, where n the number of subexpressions in s_i....

Does this need to account for one of the input senders to `when_all` sending lvalue references? I originally took this to mean `when_all(just() | then() -> int& { return some_global; }))` would send `int&`, although the later section about `when_all`'s completion signatures states the returned sender sends `decay_t<V_i>&&...` and indeed in the reference impl, the returned sender sends `int&&` (its value types).

My question specifically is whether the `set_value(out_r, t_0..., t_1..., ..., t_{n-1}...)` needs any rephrasing to indicate the decay-ed nature.

**Comment by lewissbaker** [comment]
I think the specification is now clear that `when_all` decay-copies the value results.
However, I do wonder if that is the right design.

If an operation is completing with an lvalue-ref, then presumably that reference is valid in some higher-scope than the immediate completion-signal invocation. Force-decay-copying in the case where you just wanted to obtain a reference to some object is going to force people to do workarounds like returning a pointer instead of reference (and then dealing with nullptrs), or wrapping references in reference_wrapper (and dealing with having to unwrap later).
Note that #264 might give a better solution to allowing propagation of lvalue/rvalue/prvalue results through completion functions and algorithms.
